export default async function previewNavigationChecks(page) {
  const originalViewport = await page.evaluate(() => ({width: innerWidth, height: innerHeight}))
  const errors = []
  const capture = message => { if (message.type() === 'error') errors.push(message.text()) }
  page.on('console', capture)
  try {
    await page.setViewportSize({width:1440,height:900})
    await page.goto('http://127.0.0.1:4318/?scenario=thinking&theme=light')
    const toc = page.getByRole('navigation',{name:'场景目录'})
    await toc.waitFor()
    if (await toc.getByRole('link').count() !== 24) throw Error('Missing scenarios')
    if (await page.getByRole('combobox',{name:'预览场景'}).count()) throw Error('Old dropdown remains')
    if (await toc.getByRole('link',{name:'思考中',exact:true}).getAttribute('aria-current') !== 'page') throw Error('Current scenario not marked')
    await toc.getByRole('link',{name:'工具执行中',exact:true}).click()
    await page.waitForURL('**scenario=tools&theme=light')
    const theme = page.getByRole('combobox',{name:'预览主题'})
    await theme.click()
    await page.getByRole('listbox').waitFor()
    await page.keyboard.press('Escape')
    if (!await theme.evaluate(element => element === document.activeElement)) throw Error('Theme focus not restored')
    await theme.click()
    await page.getByRole('option',{name:'深色',exact:true}).click()
    await page.waitForURL('**scenario=tools&theme=dark')
    await toc.getByRole('link',{name:'产物卡片',exact:true}).focus()
    await page.keyboard.press('Enter')
    await page.waitForURL('**scenario=artifacts&theme=dark')
    await page.reload()
    await toc.getByRole('link',{name:'产物卡片',exact:true}).waitFor()
    await page.getByRole('button',{name:'重置',exact:true}).click()
    await page.waitForURL('**scenario=artifacts&theme=dark')
    await page.setViewportSize({width:380,height:800})
    await toc.waitFor({state:'hidden'})
    const toggle = page.getByRole('button',{name:'场景目录',exact:true})
    await toggle.click()
    await toc.waitFor()
    await toc.getByRole('link',{name:'新会话',exact:true}).click()
    await page.waitForURL('**scenario=welcome&theme=dark')
    await toc.waitFor({state:'hidden'})
    await toggle.click()
    await toc.waitFor()
    await page.screenshot({path:'output/playwright/previewTocNarrow.png'})
    await toggle.click()
    await toc.waitFor({state:'hidden'})
    if (await page.evaluate(() => document.documentElement.scrollWidth>innerWidth || document.documentElement.scrollHeight>innerHeight)) throw Error('Narrow navigation overflows')
    if (errors.length) throw Error(errors.join('\n'))
    return 'PREVIEW_NAVIGATION_OK'
  } finally {
    page.off('console', capture)
    await page.setViewportSize(originalViewport)
  }
}
