export default async function previewSelectChecks(page) {
  const errors = []
  const capture = message => { if (message.type() === 'error') errors.push(message.text()) }
  page.on('console', capture)
  try {
    await page.setViewportSize({width: 760, height: 900})
    await page.goto('http://127.0.0.1:4318/?scenario=conversation&theme=light')
    const trigger = page.getByRole('combobox', {name:'预览场景'})
    await trigger.click()
    const list = page.getByRole('listbox')
    await list.waitFor()
    const metrics = await list.evaluate(element => ({height:element.getBoundingClientRect().height,font:getComputedStyle(element.querySelector('[role=option]')).fontSize}))
    if (metrics.height > 360 || metrics.font !== '12px') throw Error(JSON.stringify(metrics))
    await list.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
    await page.screenshot({path:'output/playwright/shadcnSelectLight.png'})
    await page.keyboard.press('Escape')
    if (!await trigger.evaluate(element => element === document.activeElement)) throw Error('Focus did not return after Escape')
    await trigger.press('ArrowDown')
    await list.waitFor()
    await page.keyboard.press('Home')
    await page.waitForFunction(() => document.activeElement?.textContent === '完成回复')
    await page.keyboard.press('ArrowDown')
    await page.waitForFunction(() => document.activeElement?.textContent === '多次搜索与进度说明')
    await page.keyboard.press('Enter')
    await page.waitForURL('**scenario=progressUpdates&theme=light')
    await page.getByRole('combobox',{name:'预览主题'}).click()
    await page.getByRole('option',{name:'深色',exact:true}).click()
    await page.waitForURL('**scenario=progressUpdates&theme=dark')
    await page.reload()
    await page.getByRole('combobox',{name:'预览场景'}).filter({hasText:'多次搜索与进度说明'}).waitFor()
    await page.setViewportSize({width:380,height:800})
    await page.getByRole('combobox',{name:'预览场景'}).click()
    await list.waitFor()
    const box = await list.boundingBox()
    if (!box || box.x < 0 || box.x + box.width > 380 || box.height > 360) throw Error('Menu exceeds narrow viewport')
    await list.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
    await page.screenshot({path:'output/playwright/shadcnSelectDark.png'})
    await page.keyboard.press('End')
    await page.waitForFunction(() => document.activeElement?.textContent === '产物卡片')
    await page.keyboard.press('Enter')
    await page.waitForURL('**scenario=artifacts&theme=dark')
    await page.getByRole('combobox',{name:'预览场景'}).click()
    await page.mouse.click(370,650)
    await list.waitFor({state:'hidden'})
    if (errors.length) throw Error(errors.join('\n'))
    return 'SHADCN_SELECT_OK: mouse, keyboard, Escape/focus, scroll, theme, reload, narrow layout and CSP'
  } finally {
    page.off('console', capture)
    const cdp = await page.context().newCDPSession(page)
    await cdp.send('Emulation.clearDeviceMetricsOverride')
    await cdp.detach()
  }
}
