// Run against the existing preview browser, never launch another browser here.
export default async function sessionCommandsChecks(page) {
  const errors = []
  const collect = message => { if (message.type() === 'error') errors.push(message.text()) }
  page.on('console', collect)
  const openCommand = async id => {
    const back = page.getByRole('button',{name:'返回普通对话',exact:true})
    if (await back.count()) await back.click()
    await page.locator('#prompt').fill('/')
    await page.getByRole('combobox', {name:'搜索会话命令',exact:true}).fill(id)
    await page.locator(`[cmdk-item][data-value="${id}"]`).click()
  }
  try {
    for (const [theme, width] of [['light',1440],['dark',380]]) {
      await page.setViewportSize({width,height:900})
      await page.goto(`http://127.0.0.1:4318/?scenario=conversation&theme=${theme}`)
      if (await page.getByRole('button',{name:/^(会话工具|会话命令)$/}).count()) throw Error('Legacy session entry still exists')
      await page.locator('#prompt').fill('/unknown')
      await page.getByText('没有匹配的命令，按 Esc 返回修改。',{exact:true}).waitFor()
      await page.getByRole('combobox',{name:'搜索会话命令',exact:true}).press('Escape')
      if (await page.locator('#prompt').inputValue() !== '/unknown') throw Error('Escape lost draft')
      if (await page.evaluate(() => window.viewActions.some(action => action.type === 'send'))) throw Error('Slash command reached model')
      await openCommand('catalog')
      const dialog = page.getByRole('dialog')
      if (await page.evaluate(() => window.viewActions.some(action => action.type === 'loadCatalog'))) throw Error('Opening catalog fetched data')
      const selector = page.getByRole('combobox',{name:'目录类型'})
      await selector.click()
      await page.getByRole('option',{name:'运行环境',exact:true}).hover()
      await page.screenshot({animations:'disabled',path:`output/playwright/slashCatalog-${theme}.png`})
      await page.keyboard.press('Escape')
      if (!await selector.evaluate(node => node === document.activeElement)) throw Error('Select focus not restored')
      await page.getByRole('button',{name:'刷新目录',exact:true}).click()
      await page.getByText('Node.js',{exact:true}).waitFor()
      await page.getByRole('button',{name:'关闭',exact:true}).click()
      await dialog.waitFor({state:'hidden'})
      if (await page.locator('#prompt').inputValue() !== '') throw Error('Selected slash command was not consumed')
      await openCommand('delete')
      await page.getByRole('region',{name:'确认操作'}).waitFor()
      await page.getByRole('button',{name:'取消',exact:true}).click()
      if (await page.evaluate(() => window.viewActions.some(action => action.type === 'manageThread'))) throw Error('Cancel mutated thread')
      await openCommand('shell')
      await page.getByRole('textbox',{name:'Shell 命令输入',exact:true}).fill('echo fixture')
      await page.getByRole('button',{name:'检查命令',exact:true}).click()
      await page.getByRole('dialog',{name:'确认执行 Shell 命令'}).waitFor()
      await page.getByRole('button',{name:'取消',exact:true}).click()
      if (await page.evaluate(() => window.viewActions.some(action => action.type === 'shellCommand'))) throw Error('Shell ran before confirmation')
      if (await page.locator('#prompt').inputValue() !== 'echo fixture') throw Error('Shell cancel lost draft')
      await openCommand('ask')
      if (await page.locator('#prompt').inputValue() !== '') throw Error('Shell draft leaked into side question')
      await page.getByRole('button',{name:'返回普通对话',exact:true}).click()
      if (await page.locator('#prompt').inputValue() !== '') throw Error('Shell draft leaked into the ordinary composer')
      await page.goto(`http://127.0.0.1:4318/?scenario=commandFailure&theme=${theme}`)
      await openCommand('ask')
      await page.getByRole('textbox',{name:'旁路提问输入',exact:true}).fill('保留这条问题')
      await page.getByRole('button',{name:'发送旁路提问',exact:true}).click()
      await page.getByText('输入提交失败（模拟）。内容保留，可以重试。',{exact:true}).waitFor()
      if (await page.locator('#prompt').inputValue() !== '保留这条问题') throw Error('Failed receipt removed draft')
      await page.goto(`http://127.0.0.1:4318/?scenario=tools&theme=${theme}`)
      await openCommand('steer')
      await page.getByRole('textbox',{name:'补充指令输入',exact:true}).fill('先检查测试')
      await page.getByRole('button',{name:'发送补充指令',exact:true}).click()
      await page.getByText('已接收输入（模拟），未请求真实模型或执行命令。',{exact:true}).waitFor()
      const steers = await page.evaluate(() => window.viewActions.filter(action => action.type === 'steer'))
      if (steers.length !== 1 || !steers[0].threadId) throw Error('Steer not bound to current thread')
      await page.getByRole('button',{name:'停止生成',exact:true}).click()
      if (await page.getByRole('button',{name:'发送补充指令',exact:true}).isEnabled()) throw Error('Steer stayed enabled after completion')
      await page.screenshot({animations:'disabled',path:`output/playwright/slashInput-${theme}.png`})
      await page.getByRole('button',{name:'返回普通对话',exact:true}).click()
    }
    await page.setViewportSize({width:380,height:480})
    await page.goto('http://127.0.0.1:4318/?scenario=sideQuestionFailed&theme=dark')
    await page.getByRole('region',{name:'旁路问答'}).waitFor()
    await page.locator('#prompt').fill('/')
    const searchBounds = await page.getByRole('combobox',{name:'搜索会话命令'}).boundingBox()
    const headerBounds = await page.locator('header').boundingBox()
    if (!searchBounds || !headerBounds || searchBounds.y < headerBounds.y + headerBounds.height || searchBounds.y + searchBounds.height > 480) throw Error('Short window hides command search')
    await page.getByRole('combobox',{name:'搜索会话命令'}).press('Escape')
    const panel = { id: 'rewind-checkpoint', kind: 'rewind', title: '选择回退检查点', description: '临时检查点', detail: null, choices: [{ id: 'first', label: '首次发送', description: '1 个文件', selected: false }], backChoiceId: null, initialText: '', multiple: false, allowText: false, confirmLabel: '继续' }
    const showPanel = value => page.evaluate(panel => window.dispatchEvent(new MessageEvent('message', { data: { type: 'panel', panel } })), value)
    await showPanel(panel)
    await page.getByRole('combobox', { name: '回退选项' }).click()
    await page.getByRole('option', { name: '首次发送' }).click()
    await page.getByRole('button', { name: '继续', exact: true }).click()
    const checkpoint = await page.evaluate(() => window.viewActions.findLast(action => action.type === 'panelReply'))
    if (checkpoint.cancelled || checkpoint.choiceIds[0] !== 'first') throw Error('Checkpoint selection was lost')
    await showPanel({ ...panel, id: 'rewind-scope', title: '确认回退范围', choices: [{ id: 'conversation', label: '只回退对话', description: '', selected: false }], confirmLabel: '确认回退' })
    await page.getByRole('combobox', { name: '回退选项' }).click()
    await page.getByRole('option', { name: '只回退对话' }).click()
    await page.screenshot({ animations: 'disabled', path: 'output/playwright/capabilityRewind-dark.png' })
    await page.getByRole('button', { name: '确认回退', exact: true }).click()
    const scope = await page.evaluate(() => window.viewActions.findLast(action => action.type === 'panelReply'))
    if (scope.cancelled || scope.choiceIds[0] !== 'conversation') throw Error('Scope selection was lost')
    await showPanel({ ...panel, id: 'rewind-cancel' })
    await page.getByRole('button', { name: '取消回退', exact: true }).click()
    if (!await page.evaluate(() => window.viewActions.findLast(action => action.type === 'panelReply').cancelled)) throw Error('Rewind cancel missing')
    await showPanel(null)
    if (errors.length) throw Error(errors.join('\n'))
    return 'SESSION_COMMANDS_UI_OK'
  } finally { page.off('console', collect) }
}
