export default async function sessionToolsChecks(page) {
  const errors = []
  const collect = message => { if (message.type() === 'error') errors.push(message.text()) }
  page.on('console', collect)
  const publish = async (patch) => page.evaluate(value => { Object.assign(window.demo, value); window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) }, patch)
  try {
    for (const [theme, width] of [['light', 1440], ['dark', 380]]) {
      await page.setViewportSize({ width, height: 900 })
      await page.goto(`http://127.0.0.1:4318/?scenario=conversation&theme=${theme}`)
      const trigger = page.getByRole('button', { name: '会话工具', exact: true })
      await trigger.click()
      const dialog = page.getByRole('dialog', { name: '会话工具', exact: true })
      await dialog.waitFor()
      if (await page.evaluate(() => window.viewActions.some(action => action.type === 'loadCatalog'))) throw Error('Opening tools must not fetch catalogs')
      const selector = page.getByRole('combobox', { name: '目录类型' })
      await selector.click(); await page.getByRole('listbox').waitFor()
      await page.screenshot({ path: `output/playwright/capabilityCatalog-${theme}.png` })
      await page.keyboard.press('Escape')
      if (!await selector.evaluate(node => node === document.activeElement)) throw Error('Select focus not restored')
      await selector.click(); await page.getByRole('option', { name: '运行环境', exact: true }).click()
      await page.getByRole('button', { name: '刷新目录', exact: true }).click()
      if (!await page.evaluate(() => window.viewActions.some(action => action.type === 'loadCatalog' && action.kind === 'environment'))) throw Error('Catalog action missing')
      await page.getByRole('button', { name: '删除', exact: true }).click()
      await page.getByRole('region', { name: '确认操作' }).waitFor()
      await page.getByRole('button', { name: '取消', exact: true }).click()
      if (await page.evaluate(() => window.viewActions.some(action => action.type === 'manageThread'))) throw Error('Cancel must not mutate')
      await page.getByRole('textbox', { name: '会话工具输入' }).fill('保留这条问题')
      await page.getByRole('button', { name: '提交', exact: true }).click()
      const request = await page.evaluate(() => window.viewActions.findLast(action => action.type === 'askSideQuestion'))
      if (!request?.threadId) throw Error('Side question must bind current thread')
      await publish({ sessionTools: { ...(await page.evaluate(() => window.demo.sessionTools)), result: { requestId: request.requestId, accepted: false } } })
      if (await page.getByRole('textbox', { name: '会话工具输入' }).inputValue() !== '保留这条问题') throw Error('Failure lost draft')
      await page.getByRole('button', { name: '提交', exact: true }).click()
      const second = await page.evaluate(() => window.viewActions.findLast(action => action.type === 'askSideQuestion'))
      await page.getByRole('textbox', { name: '会话工具输入' }).fill('发送期间的新编辑')
      await publish({ sessionTools: { ...(await page.evaluate(() => window.demo.sessionTools)), result: { requestId: second.requestId, accepted: true } } })
      if (await page.getByRole('textbox', { name: '会话工具输入' }).inputValue() !== '发送期间的新编辑') throw Error('Old receipt removed new edit')
      const contained = await dialog.evaluate(node => {
        const outer = node.getBoundingClientRect(), body = node.querySelector('.sessionToolsBody').getBoundingClientRect()
        return body.top >= outer.top && body.bottom <= outer.bottom && body.height > 100
      })
      if (!contained) throw Error('Tools body must scroll inside dialog')
      const bounds = await dialog.boundingBox()
      if (!bounds || bounds.x < 0 || bounds.x + bounds.width > width + 1 || bounds.height > 901) throw Error('Dialog overflows viewport')
      await page.screenshot({ path: `output/playwright/capabilityTools-${theme}.png` })
      await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' })
      if (!await trigger.evaluate(node => node === document.activeElement)) throw Error('Dialog focus not restored')
    }
    const panel = { id: 'rewind-checkpoint', kind: 'rewind', title: '选择回退检查点', description: '临时检查点', detail: null, choices: [{ id: 'first', label: '首次发送', description: '1 个文件', selected: false }], backChoiceId: null, initialText: '', multiple: false, allowText: false, confirmLabel: '继续' }
    const showPanel = value => page.evaluate(panel => window.dispatchEvent(new MessageEvent('message', { data: { type: 'panel', panel } })), value)
    await showPanel(panel)
    await page.getByRole('combobox', { name: '回退选项' }).click()
    await page.getByRole('option', { name: '首次发送' }).click()
    await page.getByRole('button', { name: '继续', exact: true }).click()
    const checkpoint = await page.evaluate(() => window.viewActions.findLast(action => action.type === 'panelReply'))
    if (checkpoint.cancelled || checkpoint.choiceIds[0] !== 'first') throw Error('Checkpoint selection was lost')
    await showPanel({ ...panel, id: 'rewind-scope', title: '确认回退范围', choices: [{ id: 'conversation', label: '只回退对话', description: '', selected: false }], confirmLabel: '确认回退' })
    await page.getByRole('combobox', { name: '回退选项' }).click()
    await page.getByRole('option', { name: '只回退对话' }).click()
    await page.screenshot({ path: 'output/playwright/capabilityRewind-dark.png' })
    await page.getByRole('button', { name: '确认回退', exact: true }).click()
    const scope = await page.evaluate(() => window.viewActions.findLast(action => action.type === 'panelReply'))
    if (scope.cancelled || scope.choiceIds[0] !== 'conversation') throw Error('Scope selection was lost')
    await showPanel({ ...panel, id: 'rewind-cancel' })
    await page.getByRole('button', { name: '取消回退', exact: true }).click()
    if (!await page.evaluate(() => window.viewActions.findLast(action => action.type === 'panelReply').cancelled)) throw Error('Rewind cancel missing')
    await showPanel(null)
    if (errors.length) throw Error(errors.join('\n'))
    return 'SESSION_TOOLS_UI_OK'
  } finally { page.off('console', collect) }
}
