// Reuse one preview page. Opening tasks never posts a Host action or starts Core.
export default async function taskProgressPreviewChecks(page) {
  const errors = []
  const capture = error => errors.push(String(error))
  page.on('pageerror', capture)
  const expect = (value, message) => { if (!value) throw Error(message) }
  const trigger = page.locator('.taskProgressTrigger')
  const panel = page.getByRole('dialog', { name: '任务进展', exact: true })
  try {
    await page.goto('http://127.0.0.1:4318/?scenario=waitingForHost')
    expect(await trigger.count() === 0, 'Task button flashed before receiving a plan')
    for (const [theme, width, height] of [['light', 1200, 900], ['dark', 380, 700], ['light', 320, 600]]) {
      await page.setViewportSize({ width, height })
      await page.goto(`http://127.0.0.1:4318/?scenario=taskProgress&theme=${theme}`)
      await trigger.waitFor()
      expect(await trigger.innerText() === '任务\n1 / 3', 'Incorrect task summary')
      expect(await page.locator('.taskProgressCard').count() === 0, 'Old per-call task cards remain')
      expect(!await panel.isVisible(), 'Task panel should start closed')
      await page.evaluate(() => {
        window.demo.messages.push({ id: 'scroll-fixture', role: 'assistant', label: 'CodeM', text: Array.from({ length: 40 }, (_, i) => `滚动验证段落 ${i + 1}：查看聊天内容时，任务入口保持在右侧。`).join('\n\n') })
        window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) }))
        const scroller = document.querySelector('#scrollArea')
        scroller.scrollTop = Math.floor((scroller.scrollHeight - scroller.clientHeight) / 2)
        scroller.dispatchEvent(new Event('scroll'))
      })
      const jump = page.getByRole('button', { name: '回到最新消息', exact: true })
      await jump.waitFor()
      const layout = await page.locator('#composer').boundingBox()
      const anchor = await trigger.boundingBox()
      expect(anchor.height === 30, 'Task button lost its intended height')
      expect(await trigger.evaluate(node => !/^(transparent|rgba\()|\//.test(getComputedStyle(node).backgroundColor)), 'Closed task button has a transparent background')
      expect(anchor.y + anchor.height <= layout.y && layout.y - anchor.y - anchor.height <= 12, 'Task button is not above composer')
      const jumpBounds = await jump.boundingBox()
      expect(Math.abs(anchor.y + anchor.height / 2 - jumpBounds.y - jumpBounds.height / 2) <= 1, 'Tasks and jump button are not level')
      expect(anchor.x >= jumpBounds.x + jumpBounds.width + 8, 'Task button overlaps the jump button')
      expect(Math.abs(anchor.x + anchor.width - layout.x - layout.width) <= 1, 'Task button is not aligned to the right edge of composer')
      const scrollTop = await page.locator('#scrollArea').evaluate(node => node.scrollTop)
      const plan = await page.evaluate(() => structuredClone(window.demo.capabilities.plan))
      await page.evaluate(() => { window.demo.capabilities.plan = []; window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) })
      expect(JSON.stringify(layout) === JSON.stringify(await page.locator('#composer').boundingBox()), 'Removing tasks resized composer')
      expect(await page.locator('#scrollArea').evaluate(node => node.scrollTop) === scrollTop, 'Removing tasks moved transcript')
      await page.evaluate(plan => { window.demo.capabilities.plan = plan; window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) }, plan)
      expect(JSON.stringify(layout) === JSON.stringify(await page.locator('#composer').boundingBox()), 'Showing tasks resized composer')
      expect(await page.locator('#scrollArea').evaluate(node => node.scrollTop) === scrollTop, 'Showing tasks moved transcript')
      await page.screenshot({ animations: 'disabled', path: `output/playwright/task-position-${theme}-${width}.png` })
      const calls = await page.evaluate(() => window.viewActions.length)
      await trigger.focus(); await page.keyboard.press('Enter')
      await panel.waitFor()
      expect(await trigger.evaluate(node => !/^(transparent|rgba\()|\//.test(getComputedStyle(node).backgroundColor)), 'Open task button has a transparent background')
      expect(await page.locator('.taskProgressList li').count() === 3, 'Current task list is incomplete')
      expect(await page.locator('.taskProgressList [data-task-state=completed]').count() === 1, 'Wrong completion count')
      expect(await page.locator('.taskProgressList [data-task-state=in_progress]').count() === 1, 'Missing active task')
      expect(await page.evaluate(() => window.viewActions.length) === calls, 'Opening tasks sent a Host request')
      expect(JSON.stringify(layout) === JSON.stringify(await page.locator('#composer').boundingBox()), 'Opening tasks shifted composer')
      expect(await page.locator('#scrollArea').evaluate(node => node.scrollTop) === scrollTop, 'Opening tasks moved transcript')
      expect(!await page.locator('body').evaluate(node => node.hasAttribute('data-scroll-locked')), 'Task popup locked chat scrolling')
      const bounds = await panel.boundingBox()
      expect(bounds.x >= 11 && bounds.x + bounds.width <= width - 11 && bounds.y >= 11 && bounds.y + bounds.height <= anchor.y, 'Task panel escaped the viewport or opened below the input')
      await page.screenshot({ animations: 'disabled', path: `output/playwright/task-progress-${theme}-${width}.png` })
      const scrollBounds = await page.locator('#scrollArea').boundingBox()
      await page.mouse.move(scrollBounds.x + 4, scrollBounds.y + 16)
      await page.mouse.wheel(0, 150)
      await page.waitForFunction(top => document.querySelector('#scrollArea').scrollTop > top, scrollTop)
      expect(await panel.isVisible(), 'Scrolling chat closed the task panel')
      expect(JSON.stringify(anchor) === JSON.stringify(await trigger.boundingBox()), 'Scrolling chat moved task button')
      await page.keyboard.press('Escape'); await panel.waitFor({ state: 'hidden' })
      expect(await trigger.evaluate(node => node === document.activeElement), 'Escape failed to return focus')
      await jump.click()
      await jump.waitFor({ state: 'hidden' })
      expect(await trigger.isVisible(), 'Jumping to latest hid tasks')
      expect(JSON.stringify(anchor) === JSON.stringify(await trigger.boundingBox()), 'Jumping to latest moved task button')
      expect(await page.locator('#scrollArea').evaluate(node => node.scrollHeight - node.scrollTop - node.clientHeight < 2), 'Jumping to latest did not reach bottom')
      await trigger.click(); await panel.waitFor()
      await trigger.click(); await panel.waitFor({ state: 'hidden' })
      await trigger.click(); await panel.waitFor()
      await page.evaluate(() => { window.demo.capabilities.plan[1].status = 'completed'; window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) })
      await panel.getByText('2 / 3 已完成', { exact: true }).waitFor()
      expect(await trigger.getAttribute('data-state') === 'open', 'Live update closed the task list')
      await page.evaluate(() => { window.demo.messages.push({ id: 'failed-task', role: 'tool', label: 'task_update', status: 'failed', summary: '', text: '更新失败' }); window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) })
      expect(await page.locator('.taskProgressList [data-task-state=completed]').count() === 2, 'Failed call changed authoritative progress')
      await page.evaluate(() => { window.demo.capabilities.plan = window.demo.capabilities.plan.map(task => ({ ...task, status: 'completed' })); window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) })
      await panel.getByText('3 / 3 已完成', { exact: true }).waitFor()
      await page.keyboard.press('Escape')
      expect(await trigger.isVisible(), 'Completed task list disappeared')
      if (width === 380) {
        await page.evaluate(() => { window.demo.capabilities.plan = Array.from({ length: 30 }, (_, i) => ({ content: `待执行任务 ${i + 1}`, status: 'pending' })); window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) })
        await trigger.click(); await panel.waitFor()
        const chatTop = await page.locator('#scrollArea').evaluate(node => node.scrollTop)
        const list = page.locator('.taskProgressList')
        const listBounds = await list.boundingBox()
        await page.mouse.move(listBounds.x + listBounds.width / 2, listBounds.y + listBounds.height / 2)
        await page.mouse.wheel(0, 300)
        await page.waitForFunction(() => document.querySelector('.taskProgressList').scrollTop > 0)
        expect(await page.locator('#scrollArea').evaluate(node => node.scrollTop) === chatTop, 'Scrolling tasks moved chat')
      }
      await page.reload(); await trigger.waitFor()
      expect(!await panel.isVisible(), 'Reload kept transient open state')
      await trigger.click(); await panel.waitFor()
      await page.evaluate(() => { window.demo.threadId = 'different-thread'; window.demo.capabilities.plan = [{ content: '另一会话任务', status: 'pending' }]; window.dispatchEvent(new MessageEvent('message', { data: structuredClone(window.demo) })) })
      await panel.waitFor({ state: 'hidden' })
      await trigger.click(); await panel.getByText('另一会话任务', { exact: true }).waitFor()
      expect(await panel.getByText('实现登录页面', { exact: true }).count() === 0, 'Old session tasks leaked')
      await page.keyboard.press('Escape')
      await page.getByRole('button', { name: '新建会话', exact: true }).click()
      await trigger.waitFor({ state: 'detached' })
    }
    expect(errors.length === 0, errors.join('\n'))
    return 'TASK_PROGRESS_OK: right-side placement, scroll alignment and stability, both themes, keyboard/focus, no RPC, live updates, failure, completion, reload and context cleanup'
  } finally { page.off('pageerror', capture) }
}
