/** Run in the existing preview browser session. The two scenes are explicit UI fixtures. */
export async function verifyManagementFlows(page) {
  const base = await page.evaluate(() => location.origin)
  await page.goto(`${base}/?host=vscode&scene=search`)
  const search = page.getByRole('button', { name: '搜索当前会话正文' })
  await search.click()
  const query = page.getByRole('textbox', { name: '正文关键词' })
  await query.fill('Orion'); await query.press('Enter')
  const hit = page.getByRole('button', { name: /CodeM 早期会话/ })
  await hit.waitFor({ state: 'visible' }); await hit.click()
  await page.locator('.message.searchTarget').waitFor({ state: 'visible' })
  await page.getByRole('button', { name: '回到最新消息', exact: true }).click()
  await page.locator('.message.searchTarget').waitFor({ state: 'detached' })
  await search.click(); await query.fill('不存在'); await query.press('Enter')
  await page.getByRole('status').filter({ hasText: '0 条匹配' }).waitFor({ state: 'visible' })
  await query.fill('失败'); await query.press('Enter')
  await page.getByRole('alert').filter({ hasText: '搜索失败' }).waitFor({ state: 'visible' })
  await page.keyboard.press('Escape'); await page.getByRole('dialog').waitFor({ state: 'hidden' })
  if (!await search.evaluate(node => node === document.activeElement)) throw new Error('Search focus did not return to trigger')
  await page.goto(`${base}/?host=vscode&scene=plugins`)
  const trigger = page.getByRole('button', { name: '管理插件与技能' })
  await trigger.click()
  const dialog = page.getByRole('dialog')
  await dialog.getByText('尚未安装插件。', { exact: true }).waitFor({ state: 'visible' })
  const spec = page.getByRole('textbox', { name: '插件市场安装标识' })
  await spec.fill('missing@fixture'); await spec.press('Enter')
  await page.getByRole('alert').filter({ hasText: '插件来源不存在' }).waitFor({ state: 'visible' })
  await spec.fill('sample@fixture'); await spec.press('Enter')
  await dialog.getByRole('button', { name: '禁用', exact: true }).click()
  await dialog.getByRole('button', { name: '启用', exact: true }).click()
  await dialog.getByRole('button', { name: '卸载', exact: true }).click()
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await dialog.getByRole('button', { name: '卸载', exact: true }).click()
  await dialog.getByRole('button', { name: '确认卸载', exact: true }).click()
  await dialog.getByText('尚未安装插件。', { exact: true }).waitFor({ state: 'visible' })
  for (const width of [420, 1000]) {
    await page.setViewportSize({ width, height: 780 })
    const bounds = await dialog.boundingBox()
    if (!bounds || bounds.x < 0 || bounds.x + bounds.width > width + 1 || bounds.y < 0 || bounds.y + bounds.height > 781) throw new Error('Management dialog overflows viewport')
  }
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' })
  if (!await trigger.evaluate(node => node === document.activeElement)) throw new Error('Plugin focus did not return to trigger')
  return 'MANAGEMENT_FLOWS_OK'
}
